
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ian
 */
public class att_GUI extends javax.swing.JFrame {

    /**
     * Creates new form att_GUI
     */
    public att_GUI() {
        initComponents();
        this.setLocationRelativeTo(null);//to locate center on the screen.
        jPvatt.setVisible(false);
        
        showDate();
        showTime();
    }
    void showDate(){
        Date d = new Date();
        SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
        datelab.setText(f.format(d));
        
    }
    void showTime(){
        new Timer(0, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                timelab.setText(s.format(d));
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jtxtsearch = new javax.swing.JTextField();
        jbtnsearch = new javax.swing.JButton();
        jbtnadd = new javax.swing.JButton();
        jbtnupdate = new javax.swing.JButton();
        jbtndel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        datelab = new javax.swing.JLabel();
        timelab = new javax.swing.JLabel();
        timelab1 = new javax.swing.JLabel();
        jPdtbase = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbdatabase = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelclose = new javax.swing.JLabel();
        jLmini = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtnlogout = new javax.swing.JButton();
        jPvatt = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jtxtsearch.setBackground(new java.awt.Color(204, 204, 204));
        jtxtsearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtxtsearch.setToolTipText("Student ID");

        jbtnsearch.setText("SEARCH");
        jbtnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsearchActionPerformed(evt);
            }
        });

        jbtnadd.setText("ADD");
        jbtnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddActionPerformed(evt);
            }
        });

        jbtnupdate.setText("UPDATE");
        jbtnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnupdateActionPerformed(evt);
            }
        });

        jbtndel.setText("DELETE");
        jbtndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndelActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Search ID Number:");

        jButton6.setText("View Attendance");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        datelab.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        datelab.setText("DATE: ");

        timelab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        timelab.setText("TIME: ");

        timelab1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        timelab1.setText("TODAY is ,");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(timelab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(datelab, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(timelab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jbtnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jbtnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtndel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(timelab1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datelab, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(timelab, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnsearch)
                    .addComponent(jbtnadd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnupdate)
                    .addComponent(jbtndel))
                .addGap(27, 27, 27)
                .addComponent(jButton6)
                .addGap(57, 57, 57))
        );

        jtbdatabase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtbdatabase);
        jtbdatabase.getAccessibleContext().setAccessibleParent(jPdtbase);

        javax.swing.GroupLayout jPdtbaseLayout = new javax.swing.GroupLayout(jPdtbase);
        jPdtbase.setLayout(jPdtbaseLayout);
        jPdtbaseLayout.setHorizontalGroup(
            jPdtbaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPdtbaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPdtbaseLayout.setVerticalGroup(
            jPdtbaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPdtbaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton7.setText("Load Database");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("ATTENDANCE MONITORING SYSTEM");

        jLabelclose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelclose.setText("X");
        jLabelclose.setToolTipText("close tab");
        jLabelclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcloseMouseClicked(evt);
            }
        });

        jLmini.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLmini.setText("-");
        jLmini.setToolTipText("minimize tab");
        jLmini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLminiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLmini)
                .addGap(18, 18, 18)
                .addComponent(jLabelclose, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelclose)
                    .addComponent(jLmini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnlogout.setText("LOGOUT");
        jbtnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlogoutActionPerformed(evt);
            }
        });

        jPvatt.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPvattLayout = new javax.swing.GroupLayout(jPvatt);
        jPvatt.setLayout(jPvattLayout);
        jPvattLayout.setHorizontalGroup(
            jPvattLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
        );
        jPvattLayout.setVerticalGroup(
            jPvattLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 283, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238)
                        .addComponent(jbtnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPdtbase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(287, Short.MAX_VALUE)
                    .addComponent(jPvatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtnlogout)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)))
                .addComponent(jPdtbase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(102, Short.MAX_VALUE)
                    .addComponent(jPvatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcloseMouseClicked
        NewJFrame njf = new NewJFrame();
        njf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelcloseMouseClicked

    private void jLminiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLminiMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLminiMouseClicked

    private void jbtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddActionPerformed
        jFregi regi = new jFregi();
        regi.setVisible(true);
        regi.setLocationRelativeTo(null);
        this.hide();
    }//GEN-LAST:event_jbtnaddActionPerformed

    private void jbtnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlogoutActionPerformed
       int out = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?" , "Logout" , JOptionPane.YES_NO_OPTION , JOptionPane.QUESTION_MESSAGE);
        if(out == JOptionPane.YES_OPTION){
        NewJFrame l = new NewJFrame();
        this.dispose();
        l.setVisible(true);
        }
    }//GEN-LAST:event_jbtnlogoutActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jPdtbase.setVisible(true);
        jPvatt.setVisible(false);
        jtxtsearch.setText("");
        
        //this is to clear data
        jtbdatabase.setModel(new DefaultTableModel());
        
        File file = new File("BOBO.txt");
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            
            String fline = br.readLine().trim();
            String[] c_name = fline.split(",");
            
            DefaultTableModel model = (DefaultTableModel)jtbdatabase.getModel();
            
            model.setColumnIdentifiers(c_name);
            
            Object[] tblines = br.lines().toArray();
            
            int a=0;
            
            for(int i=0 ; i<tblines.length ; i++){
                String line = tblines[i].toString().trim();
                //JOptionPane.showMessageDialog(null ,line , "ggwp" , JOptionPane.PLAIN_MESSAGE);
                String[] dtrow = line.split("/");
                //lname[a] = dtrow[0];
                
                model.addRow(dtrow);
                //JOptionPane.showMessageDialog(null , dtrow[0], "ggwp" , JOptionPane.PLAIN_MESSAGE);
                
            }
            
        } catch (Exception ex) {
            Logger.getLogger(att_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jbtnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsearchActionPerformed
        String sID = jtxtsearch.getText();
        
        if(sID.isBlank()){
        JOptionPane.showMessageDialog(null , "Please fill out the search text box.","Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        
        
        else{
        //this is to clear data
        jtbdatabase.setModel(new DefaultTableModel());
        
        char[] arrid = sID.toCharArray();
        
        File file = new File("BOBO.txt");
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            
            String fline = br.readLine().trim();
            String[] c_name = fline.split(",");
            
            DefaultTableModel model = (DefaultTableModel)jtbdatabase.getModel();
            
            model.setColumnIdentifiers(c_name);
            
            Object[] tblines = br.lines().toArray();
           
            int count=0 , cc=0;
            
            
            for(int i=0 ; i<tblines.length ; i++){
                
                String line = tblines[i].toString().trim();
                //JOptionPane.showMessageDialog(null ,line , "ggwp" , JOptionPane.PLAIN_MESSAGE);
                String[] dtrow = line.split("/");
                
                
                char[] row = dtrow[0].toCharArray();
                
                //JOptionPane.showMessageDialog(null , dtrow[i] , "ggwp" , JOptionPane.PLAIN_MESSAGE);
                for(int x=0 ; x<arrid.length ; x++){
                    //JOptionPane.showMessageDialog(null , arrid[i]+"=="+row[i] , null , JOptionPane.PLAIN_MESSAGE);
                    if(arrid[x] == row[x])
                        count++;
                }
             
                if(count == arrid.length){
                model.addRow(dtrow);
                cc = count;
                count = 0;
                
                //JOptionPane.showMessageDialog(null , dtrow, "ggwp" , JOptionPane.PLAIN_MESSAGE);
                }
                count = 0;
            }
            if(cc != arrid.length){
                JOptionPane.showMessageDialog(null , "\""+sID+"\" is not registered in the database, try again.", "Message" , JOptionPane.INFORMATION_MESSAGE);
            }
            count = 0;
            
        } catch (Exception ex) {
            Logger.getLogger(att_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        jtxtsearch.setText("");
        
    }//GEN-LAST:event_jbtnsearchActionPerformed
    static int count=0;
    static int f=0 , r=0 , e=0 , a=0 , l=0 , y=0 , n=0 , z=0;
    private void jbtndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndelActionPerformed
        String sID = jtxtsearch.getText();
        
        if(sID.isBlank()){
            JOptionPane.showMessageDialog(null , "Please fill out the search text box." , "Warning" , JOptionPane.WARNING_MESSAGE);
        }
        else{
            
            jtbdatabase.setModel(new DefaultTableModel());
            
            File fis = new File("BOBO.txt");
            
            String id[] = new String[100] , ln[] = new String[100] , fn[] = new String[100] , mn[] = new String[100] , gen[] = new String[100] , crs[] = new String[100] , yr[] = new String[100] , sec[] = new String[100] ;
            
            try {
                BufferedReader br = new BufferedReader(new FileReader(fis));
                
                String line = br.readLine().trim();
                String[] c_name = line.split(",");
                
                DefaultTableModel model = (DefaultTableModel)jtbdatabase.getModel();
                model.setColumnIdentifiers(c_name);
                
                Object[] tblines = br.lines().toArray();
                
               
               
               
               for(int i=0 ; i<tblines.length ; i++){
                    String lines = tblines[i].toString().trim();
                    String dtrow[] = lines.split("/");
                    //test...
                    //JOptionPane.showMessageDialog(null, dtrow.length , null, JOptionPane.PLAIN_MESSAGE);
                    for(int x=0 ; x<dtrow.length ; x++){
                        if(x == 0){
                            id[f] = dtrow[x];
                            f++;
                            count++;
                        }
                        else if(x == 1){
                            ln[r] = dtrow[x];
                            r++;
                        }
                        else if(x == 2){
                            fn[e] = dtrow[x];
                            e++;
                        }
                        else if(x == 3){
                            mn[a] = dtrow[x];
                            a++;
                        }
                        else if(x == 4){
                            gen[l] = dtrow[x];
                            l++;
                        }
                        else if(x == 5){
                            crs[y] = dtrow[x];
                            y++;
                        }
                        else if(x == 6){
                            yr[n] = dtrow[x];
                            n++;
                        }
                        else if(x == 7){
                            sec[z] = dtrow[x];
                            z++;
                        }
                    }
                    
                    //model.addRow(dtrow);
                }
               //test....
               /*for(int i=0; i<count ; i++){
                   JOptionPane.showMessageDialog(null, id[i]+", "+ln[i]+", "+fn[i]+", "+mn[i]+", "+gen[i]+", "+crs[i]+", "+yr[i]+", "+sec[i],null,JOptionPane.PLAIN_MESSAGE);
               }*/
            } catch (Exception ex) {
                Logger.getLogger(att_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            //test...
            //JOptionPane.sho,wMessageDialog(null , count, null , JOptionPane.PLAIN_MESSAGE);
            
            
            
            int p1=0 , flag=0;
            //test....
            //JOptionPane.showMessageDialog(null, count , "this is the value of ln[0]", JOptionPane.PLAIN_MESSAGE);
          
            for(int i=0 ; i<count ; i++){
                if(sID.equals(id[i])){
                    p1 = i;
                    flag++;
                    int jop = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete\n"+id[i]+","+ln[i]+","+fn[i]+","+mn[i]+","+gen[i]+","+crs[i]+","+yr[i]+","+sec[i], "Deleting.", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if(jop == JOptionPane.YES_OPTION){
                    for(int a = p1 ; a<count ; a++){
                id[a] = id[a+1];
                ln[a] = ln[a+1];
                fn[a] = fn[a+1];
                mn[a] = mn[a+1];
                gen[a] = gen[a+1];
                crs[a] = crs[a+1];
                yr[a] = yr[a+1];
                sec[a] = sec[a+1];
            }
            count--;
            JOptionPane.showMessageDialog(null , "\""+sID+"\" is successfully deleted,\nplease load the database.", "Deleted." , JOptionPane.INFORMATION_MESSAGE);
            try {
                FileOutputStream fos = new FileOutputStream("BOBO.txt");
                PrintWriter pw = new PrintWriter(fos);
                pw.print("Stud_ID,L_name,F_name,M_ini,Gender,Course,Year,Section\n");
                for(int j=0 ; j<count ; j++){
                    pw.println(id[j]+"/"+ln[j]+"/"+fn[j]+"/"+mn[j]+"/"+gen[j]+"/"+crs[j]+"/"+yr[j]+"/"+sec[j]);
                }
                pw.close();
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(att_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
                    break;
                    //test......
                    //JOptionPane.showMessageDialog(null, "located at "+p1, "tama kana ", JOptionPane.PLAIN_MESSAGE);
                }
                    else{
                        break;
                    }
                }
            }
            if(flag == 0){
                JOptionPane.showMessageDialog(null , "\""+sID+"\" is not registered in the database, try again.", "Message" , JOptionPane.INFORMATION_MESSAGE);
            }
            
            flag = 0;
            }
            
        jtxtsearch.setText("");
        count=0;
        f=0 ;
        r=0 ;
        e=0 ;
        a=0 ;
        l=0 ;
        y=0 ;
        n=0 ;
        z=0;
    }//GEN-LAST:event_jbtndelActionPerformed

    static int bilang = 0;
    static String sIDD;
    private void jbtnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnupdateActionPerformed
        sIDD = jtxtsearch.getText();
        
        if(sIDD.isBlank()){
            JOptionPane.showMessageDialog(null, "You must fill out the search text box.", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            jtbdatabase.setModel(new DefaultTableModel());
            String id[] = new String[100] ,ln[] = new String[100] ,fn[] = new String[100] ,mn[] = new String[100] ,gen[] = new String[100] ,crs[] = new String[100] ,yr[] = new String[100] ,sec[] = new String[100] ;
            
            File fos = new File("BOBO.txt");
            
            try {
                BufferedReader br = new BufferedReader(new FileReader(fos));
                
                String fline = br.readLine().trim();
                String cname[] = fline.split(",");
                
                DefaultTableModel mod = (DefaultTableModel)jtbdatabase.getModel();
                
                mod.setColumnIdentifiers(cname);
                
                Object[] tblines = br.lines().toArray();
                
                  
                
                for(int i=0 ; i<tblines.length ; i++){
                    String line = tblines[i].toString().trim();
                    String dtrow[] = line.split("/");
                    
                    for(int x = 0 ; x<dtrow.length ; x++){
                        if(x == 0){
                            id[f] = dtrow[x];
                            f++;
                            count++;
                        }
                        else if(x == 1){
                            ln[r] = dtrow[x];
                            r++;
                        }
                        else if(x == 2){
                            fn[e] = dtrow[x];
                            e++;
                        }
                        else if(x == 3){
                            mn[a] = dtrow[x];
                            a++;
                        }
                        else if(x == 4){
                            gen[l] = dtrow[x];
                            l++;
                        }
                        else if(x == 5){
                            crs[y] = dtrow[x];
                            y++;
                        }
                        else if(x == 6){
                            yr[n] = dtrow[x];
                            n++;
                        }
                        else if(x == 7){
                            sec[z] = dtrow[x];
                            z++;
                        }
                    }    
                }
            } catch (Exception ex) {
                Logger.getLogger(att_GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            int p = 0 , flag = 0;
            
            for(int i=0 ; i<count ; i++){
                if(sIDD.equals(id[i])){
                    bilang+=1;
                    p=i;
                    flag++;
                    jFregi regi = new jFregi();
                    regi.setVisible(true);
                    regi.setLocationRelativeTo(null);
                    regi.jTxtid.setText(id[i]);
                    regi.jtxtlname.setText(ln[i]);
                    regi.jtxtfname.setText(fn[i]);
                    regi.jtxtmi.setText(mn[i]);
                    regi.jComboBoxgen.setSelectedItem(gen[i]);
                    regi.jtxtcrs.setText(crs[i]);
                    regi.jtxtyr.setText(yr[i]);
                    regi.jtxtsec.setText(sec[i]);
                    
                    this.hide();
                    regi.bilan = 1;
                    /*
                    for(int a=p ; a<count ; a++){
                        id[i] = id[i+1];
                        ln[i] = ln[i+1];
                        fn[i] = fn[i+1];
                        mn[i] = mn[i+1];
                        gen[i] = gen[i+1];
                        crs[i] = crs[i+1];
                        yr[i] = yr[i+1];
                        sec[i] = sec[i+1];
                    }
                    count--;
                    try {
                        FileOutputStream ff = new FileOutputStream("BOBO.txt");
                        PrintWriter pew = new PrintWriter(ff);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(att_GUI.class.getName()).log(Level.SEVERE, null, ex);
                    }*/
                    break;
                }
            }
            if(flag == 0){
                JOptionPane.showMessageDialog(null , "\""+sIDD+"\" is not registered in the database, try again.", "Message" , JOptionPane.INFORMATION_MESSAGE);   
            }
            flag = 0;
        }
     jtxtsearch.setText("");
        count=0;
        f=0 ;
        r=0 ;
        e=0 ;
        a=0 ;
        l=0 ;
        y=0 ;
        n=0 ;
        z=0;   
    }//GEN-LAST:event_jbtnupdateActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jPdtbase.setVisible(false);
        jPvatt.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(att_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(att_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(att_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(att_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new att_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datelab;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelclose;
    private javax.swing.JLabel jLmini;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPdtbase;
    public javax.swing.JPanel jPvatt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnadd;
    private javax.swing.JButton jbtndel;
    private javax.swing.JButton jbtnlogout;
    private javax.swing.JButton jbtnsearch;
    private javax.swing.JButton jbtnupdate;
    public javax.swing.JTable jtbdatabase;
    private javax.swing.JTextField jtxtsearch;
    private javax.swing.JLabel timelab;
    private javax.swing.JLabel timelab1;
    // End of variables declaration//GEN-END:variables
}
