
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ian
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        //this.setLocationRelativeTo(null); //center on the screen
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        logpan = new javax.swing.JPanel();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbshow = new javax.swing.JCheckBox();
        btnlogin = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabelclose = new javax.swing.JLabel();
        jLmini = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        logpan.setBackground(new java.awt.Color(0, 0, 0));
        logpan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        txtuser.setBackground(new java.awt.Color(153, 153, 153));
        txtuser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtuser.setForeground(new java.awt.Color(255, 255, 255));
        txtuser.setToolTipText("ID no. / Admin");
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });

        txtpass.setBackground(new java.awt.Color(153, 153, 153));
        txtpass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtpass.setForeground(new java.awt.Color(255, 255, 255));
        txtpass.setToolTipText("PASSWORD");
        txtpass.setActionCommand("<Not Set>");
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 204, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Username:");

        jLabel3.setBackground(new java.awt.Color(255, 204, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Password:");

        cbshow.setForeground(new java.awt.Color(255, 153, 0));
        cbshow.setText("Show");
        cbshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbshowActionPerformed(evt);
            }
        });

        btnlogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnlogin.setText("LOGIN");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        btnexit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("ATTENDANCE MONITORING SYSTEM");

        javax.swing.GroupLayout logpanLayout = new javax.swing.GroupLayout(logpan);
        logpan.setLayout(logpanLayout);
        logpanLayout.setHorizontalGroup(
            logpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logpanLayout.createSequentialGroup()
                .addGroup(logpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logpanLayout.createSequentialGroup()
                        .addGroup(logpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(logpanLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(logpanLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1))
                            .addGroup(logpanLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(logpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(logpanLayout.createSequentialGroup()
                                        .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbshow))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logpanLayout.createSequentialGroup()
                                        .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(103, 103, 103)))))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logpanLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        logpanLayout.setVerticalGroup(
            logpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logpanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnexit)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(logpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(logpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbshow))
                .addGap(18, 18, 18)
                .addComponent(btnlogin)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(logpan, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Login your Account");

        jLabelclose.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelclose.setText("X");
        jLabelclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcloseMouseClicked(evt);
            }
        });

        jLmini.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLmini.setText("-");
        jLmini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLminiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(91, 91, 91)
                .addComponent(jLmini)
                .addGap(18, 18, 18)
                .addComponent(jLabelclose, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelclose)
                    .addComponent(jLmini, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    
    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        att_GUI atg = new att_GUI();
        stud_att sat = new stud_att(); 
        
        int a=0 , b=0 , c=0 , d=0 , e=0 , f=0 , g=0, h=0 , kawn=0;
        //JOptionPane.showMessageDialog(null , a , "value of a" , JOptionPane.PLAIN_MESSAGE);
        String id[] = new String[100] , ln[] = new String[100] , fn[] = new String[100] , mn[] = new String[100] , gen[] = new String[100] , crs[] = new String[100] , yr[] = new String[100] , sec[] = new String[100]; 
        String user = txtuser.getText();
        String pass = txtpass.getText();
        
        File file = new File("BOBO.txt");
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String fline = br.readLine().trim();
            String[] coln = fline.split(",");
            
            DefaultTableModel md = (DefaultTableModel)atg.jtbdatabase.getModel();
            md.setColumnIdentifiers(coln);
            
            Object[] tbline = br.lines().toArray();
            
            for(int i=0 ; i<tbline.length ; i++){
                String line = tbline[i].toString().trim();
                String[] roww = line.split("/");
                
                for(int x=0 ; x<roww.length ; x++){
                    if(x == 0){
                            id[a] = roww[x];
                            a++;
                            kawn++;
                        }
                        else if(x == 1){
                            ln[b] = roww[x];
                            b++;
                        }
                        else if(x == 2){
                            fn[c] = roww[x];
                            c++;
                        }
                        else if(x == 3){
                            mn[d] = roww[x];
                            d++;
                        }
                        else if(x == 4){
                            gen[e] = roww[x];
                            e++;
                        }
                        else if(x == 5){
                            crs[f] = roww[x];
                            f++;
                        }
                        else if(x == 6){
                            yr[g] = roww[x];
                            g++;
                        }
                        else if(x == 7){
                            sec[h] = roww[x];
                            h++;
                        }
                }
            }
            
        } catch (Exception ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        int flag=0;
        
        if(user.equals("Admin") && pass.equals("lanzfrealyn0117")){
            flag++;
            JOptionPane.showMessageDialog(null,"You are Successfully Loged in", "Access Granted.", JOptionPane.INFORMATION_MESSAGE);
            this.hide();
            //this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            att_GUI next_page = new att_GUI();
            next_page.setVisible(true);//this is to display another form...
            next_page.pack();
            next_page.setLocationRelativeTo(null);//to display at the center...
            next_page.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            next_page.jPdtbase.setVisible(true);
            next_page.jPvatt.setVisible(false);
            
            //this.dispose();//this is hide login frame...
        }
        
        else if(!user.equals("Admin") && !pass.equals("lanzfrealyn0117")){
            
            for(int i = 0 ; i<kawn ; i++){
                if(user.equals(id[i]) && pass.equals(ln[i])){
                    flag++;
                    JOptionPane.showMessageDialog(null , "You're Present" , "ATTENDANCE" , JOptionPane.INFORMATION_MESSAGE);
                    this.hide();
                    
                    sat.setVisible(true);
                    sat.setLocationRelativeTo(null);
                }
                
            }
        }
        if(flag == 0){
            JOptionPane.showMessageDialog(null, "Incorrect Username or Password, try again.", "Access Denied.", JOptionPane.ERROR_MESSAGE);
            flag=0;        
                }
    }//GEN-LAST:event_btnloginActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        int rspns = JOptionPane.showConfirmDialog(this, "Do you want to exit?" , "EXIT.", JOptionPane.YES_NO_OPTION , JOptionPane.QUESTION_MESSAGE);
        
        if(rspns == JOptionPane.YES_OPTION){
        System.exit(0); //kills all the process in the program...
        }
        
    }//GEN-LAST:event_btnexitActionPerformed

    private void cbshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbshowActionPerformed
        if(cbshow.isSelected()){
            txtpass.setEchoChar((char)0);//this is to show password.
        }
        else{
            txtpass.setEchoChar('*');
        }
    }//GEN-LAST:event_cbshowActionPerformed

    private void jLabelcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelcloseMouseClicked

    private void jLminiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLminiMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLminiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnlogin;
    private javax.swing.JCheckBox cbshow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelclose;
    private javax.swing.JLabel jLmini;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel logpan;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
